[WIP] Improve conversion
PurplePalette/sonolus-fastapi pull request #41
Opened 2022-06-15 12:53 UTC by sevenc-nanashi

2022-06-18 14:39 UTC, sevenc-nanashi commented
Closes: #40

2022-06-18 14:40 UTC, sevenc-nanashi commented
移行コードのことを完全に忘れていた

2022-06-29 13:58 UTC, Dosugamea requested changes
たぶん同じテーブルを2回作っちゃってるので それまとめてほしいのと、
pathmagicの意図かるく知りたいっす

2022-06-29 13:58 UTC, Dosugamea commented on .env_example
> +IMAGE_SERVICE_ENDPOINT="http://sonolus_image_service:8000"
うーん、こっちでビルドしたのは3000になってたんだけどなぁ まぁexampleなのでOK

2022-06-29 13:58 UTC, Dosugamea commented on alembic/versions/48db6963ab56_recreate_file_maps.py
> +        sa.Column("createdTime", sa.Integer(), nullable=False),
[alembic/versions/dcb059ce5b46_add_process_table.py](https://github.com/PurplePalette/sonolus-fastapi/pull/41/files#diff-87df574e8439d2ab3be9a95b8c46c6a8fa37c429b9fea1602a079e1fb3d2a577) と重複してると思うので いい感じに1ファイルにまとめてもろて...

2022-06-29 13:58 UTC, Dosugamea commented on tests/_pathmagic.py
> +sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../")
ごめ、ここ何やってるのか説明ほしい

2022-06-30 21:58 UTC, sevenc-nanashi commented on tests/_pathmagic.py
> +sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../")
そのままだとseeder.yaml_のやつが読めないのでディレクトリを追加してる
_pathmagicで読み込んでるのはisortとかで壊れないようにするため

2022-07-02 11:01 UTC, sevenc-nanashi commented on alembic/versions/48db6963ab56_recreate_file_maps.py
> +        sa.Column("createdTime", sa.Integer(), nullable=False),
まとめた

2022-07-02 14:51 UTC, Dosugamea approved these changes
良いと思います  コントリビュートありがとうございます

2022-07-02 14:52 UTC, merged